group:
  - files:
      - source: raw_column_definition_MOPS.md
        dest: definitions/raw_column_definition_MOPS.md
    repos:
      - wenchiehlee-investment/Python-Actions.GoodInfo.Analyzer
